### ISSUE TITLE
Waiting for too long causes most bots to fly off the map at start of match

### ISSUE THREAD

**Issue by sudocode1** [bks1b/tower-shooter#1]
Browser: Firefox
Also happening when pausing for too long

https://github.com/bks1b/tower-shooter/assets/52894745/3a1818e1-63b1-4243-80aa-5b7112dffb4a

https://github.com/bks1b/tower-shooter/assets/52894745/85a6c6b1-d379-453d-8f09-8a5daf784449

**Comment by bks1b** [comment]
Thanks, fixed in 35ee828
